# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f758803f380d704e7baa4435f1b8000eb1e72a904508622d38e9ea8239539519c174f2b2136982fdb2374542ea3b123851e53703765eb71976c6ac855955367

test:
  secret_key_base: 4edef2f23b97d043b80cd9f1f80480597d49b511c157c3f467504ae973f034707c90cf3cdd30666ceef6da01ae24c669360300886ed5d6609b265a690e07eb5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
